accumulate_grad_batches: 1
adam_epsilon: 1.0e-08
amp_level: O2
args: !!python/object:argparse.Namespace
  accumulate_grad_batches: 1
  adam_epsilon: 1.0e-08
  amp_level: O2
  batch_size: 16
  default_root_dir: null
  deterministic: 0
  distributed_backend: null
  fast_dev_run: 0
  freeze_level: 1
  gpus: 0
  is_same_smiles: 1
  label_column: measured_log_solubility_in_mols_per_litre
  learning_rate: 0.0001
  learning_rate_scheduler: linear_with_warmup
  limit_val_batches: 1.0
  masked_lm: 1
  max_epochs: 3
  max_position_embeddings: 512
  max_seq_length: 512
  min_epochs: 1
  mode: regression
  num_nodes: 1
  num_physchem_properties: 200
  num_workers: 0
  output_size: 1
  precision: 32
  pretrained_model_path: C:\Users\Hannes\AppData\Local\Temp\tmp58l83xgl\lightning_logs\version_0\checkpoints\epoch=0-step=4.ckpt
  progress_bar_refresh_rate: 25
  resume_from_checkpoint: null
  seed: 42
  smiles_column: SMILES
  test_file: D:\Code\zpyCode\03_Apps\zChemBERT\molbert\molbert\tests\test_data_regression.csv
  tiny: true
  tpu_cores: null
  train_file: D:\Code\zpyCode\03_Apps\zChemBERT\molbert\molbert\tests\test_data_regression.csv
  val_check_interval: 0.25
  valid_file: D:\Code\zpyCode\03_Apps\zChemBERT\molbert\molbert\tests\test_data_regression.csv
  warmup_proportion: 0.1
  weight_decay: 0.01
batch_size: 16
default_root_dir: null
deterministic: 0
distributed_backend: null
fast_dev_run: 0
freeze_level: 1
gpus: 0
is_same_smiles: 1
label_column: measured_log_solubility_in_mols_per_litre
learning_rate: 0.0001
learning_rate_scheduler: linear_with_warmup
limit_val_batches: 1.0
masked_lm: 1
max_epochs: 3
max_position_embeddings: 512
max_seq_length: 512
min_epochs: 1
mode: regression
num_nodes: 1
num_physchem_properties: 200
num_workers: 0
output_size: 1
precision: 32
pretrained_model_path: C:\Users\Hannes\AppData\Local\Temp\tmp58l83xgl\lightning_logs\version_0\checkpoints\epoch=0-step=4.ckpt
progress_bar_refresh_rate: 25
resume_from_checkpoint: null
seed: 42
smiles_column: SMILES
test_file: D:\Code\zpyCode\03_Apps\zChemBERT\molbert\molbert\tests\test_data_regression.csv
tiny: true
tpu_cores: null
train_file: D:\Code\zpyCode\03_Apps\zChemBERT\molbert\molbert\tests\test_data_regression.csv
val_check_interval: 0.25
valid_file: D:\Code\zpyCode\03_Apps\zChemBERT\molbert\molbert\tests\test_data_regression.csv
vocab_size: 42
warmup_proportion: 0.1
weight_decay: 0.01
